import { and, eq, inArray, or } from "drizzle-orm";
import { z } from "zod";
import { auditLogs, clientContacts, eventPackageItems, eventPackages, supplierListings, supplierProfiles } from "@/lib/db/schema";
import { requireActiveSupplierApi } from "@/lib/supplier-access";
import { isValidWhatsapp, normalizeWhatsapp } from "@/lib/whatsapp";

const item = z.object({ serviceName: z.string().trim().min(2).max(120), description: z.string().trim().max(500).optional().default(""), providerKind: z.enum(["SELF", "REGISTERED", "MANUAL"]), providerSupplierId: z.uuid().optional().or(z.literal("")), providerName: z.string().trim().max(160).optional().default(""), amountCents: z.coerce.number().int().min(1) });
const schema = z.object({ clientContactId: z.uuid().optional().or(z.literal("")), clientName: z.string().trim().min(2), clientEmail: z.email(), clientWhatsapp: z.string().trim().refine(isValidWhatsapp), venueListingId: z.uuid().optional().or(z.literal("")), eventType: z.string().trim().min(2), eventTitle: z.string().trim().min(3), eventDate: z.iso.date().optional().or(z.literal("")), eventLocation: z.string().trim().max(240).optional().default(""), sendToClient: z.boolean(), items: z.array(item).min(1).max(50) });

export async function PATCH(request: Request, { params }: { params: Promise<{ packageId: string }> }) {
  const context = await requireActiveSupplierApi(); if ("response" in context) return context.response;
  const parsed = schema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "Revise os dados do evento." }, { status: 400 });
  const { packageId } = await params; const ownerId = context.access.session.user.id; const data = parsed.data;
  const [existing] = await context.db.select().from(eventPackages).where(and(eq(eventPackages.id, packageId), eq(eventPackages.organizerSupplierId, ownerId))).limit(1);
  if (!existing) return Response.json({ error: "Evento não encontrado." }, { status: 404 });
  const contactScope = existing.clientContactId ? or(eq(clientContacts.createdBySupplierId, ownerId), eq(clientContacts.id, existing.clientContactId)) : eq(clientContacts.createdBySupplierId, ownerId);
  let contact = data.clientContactId ? (await context.db.select().from(clientContacts).where(and(eq(clientContacts.id, data.clientContactId), contactScope)).limit(1))[0] : undefined;
  if (!contact) { const whatsapp = normalizeWhatsapp(data.clientWhatsapp); [contact] = await context.db.select().from(clientContacts).where(eq(clientContacts.whatsappNumber, whatsapp)).limit(1); if (!contact) [contact] = await context.db.insert(clientContacts).values({ whatsappNumber: whatsapp, name: data.clientName, email: data.clientEmail.toLowerCase(), createdBySupplierId: ownerId }).returning(); }
  if (data.venueListingId) { const [venue] = await context.db.select({ id: supplierListings.id }).from(supplierListings).where(and(eq(supplierListings.id, data.venueListingId), eq(supplierListings.type, "VENUE"))).limit(1); if (!venue) return Response.json({ error: "Local não encontrado." }, { status: 400 }); }
  const ids = [...new Set(data.items.filter((row) => row.providerKind === "REGISTERED").map((row) => row.providerSupplierId).filter(Boolean))] as string[];
  const registered = ids.length ? await context.db.select({ id: supplierProfiles.userId, name: supplierProfiles.businessName }).from(supplierProfiles).where(and(inArray(supplierProfiles.userId, ids), eq(supplierProfiles.approvalStatus, "ACTIVE"))) : []; if (registered.length !== ids.length) return Response.json({ error: "Um fornecedor não está disponível." }, { status: 400 }); const names = new Map(registered.map((row) => [row.id, row.name]));
  const rows = data.items.map((row, sortOrder) => ({ ...row, sortOrder, providerSupplierId: row.providerKind === "SELF" ? ownerId : row.providerKind === "REGISTERED" ? row.providerSupplierId! : null, providerName: row.providerKind === "SELF" ? context.supplier.businessName : row.providerKind === "REGISTERED" ? names.get(row.providerSupplierId!)! : row.providerName || "Fornecedor informado" }));
  const subtotal = rows.reduce((sum, row) => sum + row.amountCents, 0); const fee = Math.round(subtotal * context.supplier.administrationFeeBps / 10000); const status = data.sendToClient ? "SENT" : "DRAFT";
  await context.db.update(eventPackages).set({ clientUserId: contact.userId, clientContactId: contact.id, clientName: contact.name, clientEmail: contact.email, clientWhatsapp: contact.whatsappNumber, venueListingId: data.venueListingId || null, eventType: data.eventType, eventTitle: data.eventTitle, eventDate: data.eventDate || null, eventLocation: data.eventLocation || null, status, subtotalCents: subtotal, administrationFeeBps: context.supplier.administrationFeeBps, administrationFeeCents: fee, totalCents: subtotal + fee, sentAt: data.sendToClient ? new Date() : existing.sentAt, updatedAt: new Date() }).where(eq(eventPackages.id, packageId));
  await context.db.delete(eventPackageItems).where(eq(eventPackageItems.packageId, packageId)); await context.db.insert(eventPackageItems).values(rows.map((row) => ({ packageId, serviceName: row.serviceName, description: row.description || null, providerKind: row.providerKind, providerSupplierId: row.providerSupplierId, providerName: row.providerName, amountCents: row.amountCents, sortOrder: row.sortOrder })));
  await context.db.insert(auditLogs).values({ actorUserId: ownerId, targetUserId: contact.userId, action: "SUPPLIER_EVENT_UPDATED", details: { packageId, status } }); return Response.json({ ok: true, clientLinked: Boolean(contact.userId) });
}
