import { desc, eq, inArray } from "drizzle-orm";
import { requirePageRole } from "@/lib/access";
import { getDb } from "@/lib/db";
import { eventPackageItems, eventPackages, supplierProfiles } from "@/lib/db/schema";
import { allocateClientFacingAmounts } from "@/lib/package-finance";

export default async function ClientPackagesPage() {
  const access = await requirePageRole(["CLIENT"]); const db = getDb();
  const packages = await db.select({ id: eventPackages.id, eventTitle: eventPackages.eventTitle, eventType: eventPackages.eventType, eventDate: eventPackages.eventDate, status: eventPackages.status, totalCents: eventPackages.totalCents, businessName: supplierProfiles.businessName }).from(eventPackages).innerJoin(supplierProfiles, eq(supplierProfiles.userId, eventPackages.organizerSupplierId)).where(eq(eventPackages.clientUserId, access.session.user.id)).orderBy(desc(eventPackages.createdAt));
  const items = packages.length ? await db.select().from(eventPackageItems).where(inArray(eventPackageItems.packageId, packages.map((item) => item.id))) : [];
  const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);
  return <main className="client-page"><header className="dashboard-nav"><a className="brand" href="/">bora<span>.</span></a><nav><a href="/cliente/planejamentos">Planejamentos</a><a href="/painel">Meu painel</a></nav></header><section className="client-shell"><div className="client-heading"><div><span>PROPOSTAS DE FORNECEDORES</span><h1>Meus pacotes</h1><p>Confira os serviços, valores finais e contrato do evento.</p></div></div>{packages.length ? <div className="client-package-list">{packages.map((pack) => { const visibleItems = allocateClientFacingAmounts(items.filter((item) => item.packageId === pack.id), pack.totalCents); return <article key={pack.id}><header><div><small>{pack.eventType}</small><h2>{pack.eventTitle}</h2><p>Organizado por {pack.businessName}</p></div><strong>{money(pack.totalCents)}</strong></header><table><thead><tr><th>Serviço</th><th>Fornecedor</th><th>Valor</th></tr></thead><tbody>{visibleItems.map((item) => <tr key={item.id}><td>{item.serviceName}</td><td>{item.providerName}</td><td>{money(item.clientAmountCents)}</td></tr>)}</tbody><tfoot><tr><td colSpan={2}><b>Total do pacote</b></td><td><b>{money(pack.totalCents)}</b></td></tr></tfoot></table><a href={`/cliente/pacotes/${pack.id}/contrato`}>Abrir contrato preenchido →</a></article>; })}</div> : <div className="empty-plans"><h2>Nenhum pacote recebido</h2><p>Os pacotes enviados pelos fornecedores aparecerão aqui.</p></div>}</section></main>;
}
