import { asc, eq, and } from "drizzle-orm";
import { notFound } from "next/navigation";
import { PrintContractButton } from "@/components/client/print-contract-button";
import { requirePageRole } from "@/lib/access";
import { getDb } from "@/lib/db";
import { eventPackageItems, eventPackages, supplierProfiles, userProfiles, users } from "@/lib/db/schema";
import { allocateClientFacingAmounts } from "@/lib/package-finance";

export default async function ContractPage({ params }: { params: Promise<{ packageId: string }> }) {
  const access = await requirePageRole(["CLIENT"]); const { packageId } = await params; const db = getDb();
  const [pack] = await db.select({ id: eventPackages.id, clientName: eventPackages.clientName, clientEmail: eventPackages.clientEmail, clientWhatsapp: eventPackages.clientWhatsapp, eventTitle: eventPackages.eventTitle, eventType: eventPackages.eventType, eventDate: eventPackages.eventDate, eventLocation: eventPackages.eventLocation, totalCents: eventPackages.totalCents, createdAt: eventPackages.createdAt, businessName: supplierProfiles.businessName, supplierName: users.name, supplierWhatsapp: userProfiles.whatsappNumber }).from(eventPackages).innerJoin(supplierProfiles, eq(supplierProfiles.userId, eventPackages.organizerSupplierId)).innerJoin(users, eq(users.id, eventPackages.organizerSupplierId)).leftJoin(userProfiles, eq(userProfiles.userId, eventPackages.organizerSupplierId)).where(and(eq(eventPackages.id, packageId), eq(eventPackages.clientUserId, access.session.user.id))).limit(1);
  if (!pack) notFound(); const items = allocateClientFacingAmounts(await db.select().from(eventPackageItems).where(eq(eventPackageItems.packageId, pack.id)).orderBy(asc(eventPackageItems.sortOrder)), pack.totalCents); const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);
  return <main className="contract-page"><div className="contract-actions"><a href="/cliente/pacotes">← Voltar</a><PrintContractButton /></div><article className="contract-document"><header><strong>bora curtir bora?</strong><span>CONTRATO / PROPOSTA DE EVENTO</span></header><h1>{pack.eventTitle}</h1><p>Este documento registra a proposta apresentada por <b>{pack.businessName}</b>, representada por {pack.supplierName}, ao cliente <b>{pack.clientName}</b> ({pack.clientEmail}), para a realização de {pack.eventType}{pack.eventDate ? ` em ${new Date(`${pack.eventDate}T00:00:00Z`).toLocaleDateString("pt-BR", { timeZone: "UTC" })}` : ""}{pack.eventLocation ? `, no local ${pack.eventLocation}` : ""}.</p><h2>Serviços e valores</h2><table><thead><tr><th>Serviço</th><th>Responsável</th><th>Descrição</th><th>Valor final</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.serviceName}</td><td>{item.providerName}</td><td>{item.description || "—"}</td><td>{money(item.clientAmountCents)}</td></tr>)}</tbody><tfoot><tr><td colSpan={3}><b>Total do contrato</b></td><td><b>{money(pack.totalCents)}</b></td></tr></tfoot></table><h2>Condições</h2><p>Os serviços, prazos, formas de pagamento, responsabilidades e condições de cancelamento deverão ser confirmados pelas partes antes da assinatura definitiva. Os serviços e seus valores finais estão discriminados na grade acima.</p><div className="signature-grid"><div>Contratante: {pack.clientName}</div><div>Contratada: {pack.businessName}</div></div><footer>Documento gerado pelo BORA em {new Date().toLocaleDateString("pt-BR")}.</footer></article></main>;
}
